### ISSUE TITLE
scss background 本地引入 图片不会转成base64

### ISSUE THREAD

**Issue by PlutoCA** [remaxjs/remax#1118]
**问题描述**
scss引入 图片不会转成base64

**示例代码**
```javascript
        // remax.config.js
        // 添加sass
        addCSSRule({
            name: 'sass',
            test: /\.s[ac]ss(\?.*)?$/,
            loader: require.resolve('sass-loader'),
            options: {
                implementation: require('sass')
            }
        });
        addCSSRule({
            name: 'image',
            test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
            loader: 'url-loader',
            options: {
              limit: 10240,
            }      
        });
```
```scss
  // 引用
    .add {
        width: 49px;
        height: 48px;
        background: url('./add@2x.png') no-repeat;
        background-size: contain;
    }
```

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/31099607/85945329-a04b0180-b96f-11ea-8fd6-bf622896819b.png)
