### ISSUE TITLE
[问题]关于使用weui的疑问🤔️

### ISSUE THREAD

**Issue by ybzjsxh** [remaxjs/remax#1160]
**问题描述**
请教一下大佬们，在remax项目中使用了weui，但是样式不太对，见最后。
想问下有没有什么比较好的办法使用`weui`？谢谢

**示例代码**
步骤：
1. `yarn create remax-app remax-demo`
2. 最后一步选择跨平台，然后`cd remax-demo && yarn`
3. `yarn add weui-miniprogram`
4. 修改`remax.config.js`，如下
```jsx
module.exports = {
  one: true,
  output: 'dist/' + process.env.REMAX_PLATFORM,
+  configWebpack: ({ config, webpack, addCSSRule }) => {
+   addCSSRule({
+     name: 'wxss',
+     test: /\.wxss$/,
+   });
+ },
};
```
5. 修改`app.css`，如下
```css
+ @import '../node_modules/weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss';

page {
  background: #282c34;
}
```
6. 如果在`remax.config.js`里添加`pxToRpx: true`配置，组件样式正常了，但是其他样式都被放大了

**其他信息**
![image](https://user-images.githubusercontent.com/18141198/87615260-e44a4e80-c744-11ea-9ab7-a2069447519c.png)

![image](https://user-images.githubusercontent.com/18141198/87615790-15774e80-c746-11ea-8db8-ecf77439dabd.png)
