### ISSUE TITLE
[问题]css中引用的背景图片无法被打包

### ISSUE THREAD

**Issue by army8735** [remaxjs/remax#186]
**问题描述**
支付宝小程序，css中引用的背景图片无法被打包

**示例代码**
```jsx
impoert './index.css';
class Component extends React.Component {
  render() {
    return (
      <View className="policy">
        <PlfInfo />
      </View>
    );
  }
}
```
```css
.policy{
  background:url(xxx) no-repeat center 0;
  background-size:100% auto;
}
```
相对路径绝对路径等都试过，是否rollup-plugin-url的原因？
