### ISSUE TITLE
[BUG] css字体的base64 url被修改

### ISSUE THREAD

**Issue by coppyC** [remaxjs/remax#286]
**bug 描述**
[详细地描述 bug，让大家都能理解]
```css
@font-face {font-family: "iconfont";
  src: url('//at.alicdn.com/t/font_1464999_2mokrjxjv0f.eot?t=1571376873693'); /* IE9 */
  src: url('//at.alicdn.com/t/font_1464999_2mokrjxjv0f.eot?t=1571376873693#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAAAOUAAsAAAAAB8AAAANFAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCDMgqCYII8ATYCJAMUCwwABCAFhG0HRhvGBhHVm5HIviiwm4kvp2odBwcp2GkNt7dt3QsHeR7Ew9fY78/dXUQ0mSTIopWER4ZEInQyQ0qESEiQTCL+48/vf+TaP8hrhA6agnAqb71WY2yiR3BqzQEAOwAmtznXAxsVoUZy9smjL6Q0yC7N0w/3M12K57Nvm0NkUTRl0gAnOLCKEt6B3InyDdNLHIhPiwnUGzYj1iLi0gCv8FoF4kSvlQO+plJGwkOtUN0zsGAQ/YBRm3qRBwDO05+PX3AJPEiqMngdt47DVRD0Ac8GVMt/i7wYBez9DGDDyJhBIU57TSdQuXdGVm/+Dm0JqFcrSR/wzHjOfzb8/7MczxLq/X94JCErRDVAmkawxFf4gBAh8cFACD7yETIfBs6LCa0C9XnQIXABWDKYXiSEJNrbuXxiYeu0gaPWjhkmW9iq4T6uZlTZN9XK0wJWp3BEfLw+Y+cacXWVcXGRdnmZbrhOTR8xTLcqLvoy9q5crq4yl69jrw3pu5fOly1pCxfFRbk5ytxseVb2BIV+LNsSCnCVLVmVbNvdbVs2HbmgdIGuzRldBuG0bNDt5r4t28adwHuLXV296tQei5p7fZkDLtTLC3rOv97L6xwq2eytqKrq5kHPfGCwqD9I9CmXzwuDwSIKmpfLv4KE/cHC9ya9augXBcvOQJneGLFWfWALwua8Zr0Kw3Kf1RGU8JbKB0h3SDfIj8p9xlH2P+t33N6xMgppfv/xJDTA03HxW5pQGS3i3ALwxsVms39NRhFR+S+DnOupq4rOCsUDa+yqzO1gSfyFrB9ia/e+j6RrdiihVlcJSY0hyGqNoAt+Bqo0mIdqtRah3rTN4Q06nEKJQgCmnAEIrS4haXYFWatrdMG/QZVu/6Baa6Cg3nawJmwwFng8HBmVoAX9h2hodIFWDln4Df27V1zlpoQXco4OqIuqGbjiiLxHl/zxjYgDxzTABSyHfU8wMSU0UgSRqS1L13enwtAwOzgyKkEL+g/R0Oji8nJoff+G/t0rHslrqF/IOVYOdVHNQF9F46y8dzkmf3wj4sAxDXABBux9L8HUXy+hkSKscE9tiUq5uaLifMnwAJmsCG/zhQllXKsj+o5rjj7IJqNiE1ZZEuVsBgAAAA==') format('woff2'),
  url('//at.alicdn.com/t/font_1464999_2mokrjxjv0f.woff?t=1571376873693') format('woff'),
  url('//at.alicdn.com/t/font_1464999_2mokrjxjv0f.ttf?t=1571376873693') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('//at.alicdn.com/t/font_1464999_2mokrjxjv0f.svg?t=1571376873693#iconfont') format('svg'); /* iOS 4.1- */
}
```

编译后，base64 那个ur会被修改成别的

![image](https://user-images.githubusercontent.com/25004510/67136489-5f83e000-f259-11e9-81e6-737d4e99c6cd.png)

**复现步骤**
上述代码加入css，并在 app.ts 引入css文件

**期望结果**
不要改动

**版本信息:**

- remax 版本: [e.g. 1.2.1]
- 小程序端 [e.g. 微信小程序]
- 开发环境 [e.g. mac OS]
