### ISSUE TITLE
[问题]默认情况下不支持CSS background-image 的 inline 吗？

### ISSUE THREAD

**Issue by wangkuan** [remaxjs/remax#448]
**问题描述**
我在 css 中使用 background-image 引用一个相对路径的图片，但是在微信小程序开发工具中提示CSS中图片必须是以 base64 的方式引用。
期望的结果是打包的过程会将我的 css 进行处理，把引用的图片base64内容替代掉 url 引用的部分。
是我的路径写法错误，还是默认不支持这种 inline css image 的操作呢？

**示例代码**
``` css
.logo {
  margin: 200px auto 0 auto;
  width: 400px;
  height: 140px;
  background-image: url('./images/icon_brand_normal.png');
}
```

**其他信息**
![image](https://user-images.githubusercontent.com/3745293/70127890-df092980-16b6-11ea-8870-8506c9782bfb.png)
![image](https://user-images.githubusercontent.com/3745293/70127896-e3354700-16b6-11ea-9670-cfc5ee12e568.png)
